version: '3.3'

services:
  postgres:
    image: postgres:13
    env_file:
      - .env
    environment:
      - POSTGRES_DB:${POSTGRES_DB}
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL:${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD:${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 5050:80

  mysql:
    image: mysql
    environment:
      - MYSQL_DB:${MYSQL_DB}
      - MYSQL_USER:${MYSQL_USER}
      - MYSQL_PASSWORD:${MYSQL_PASSWORD}
      - MYSQL_PORT:${MYSQL_PORT}
      - MYSQL_ALLOW_EMPTY_PASSWORD='yes'
    ports:
      - 3307:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

